### PR TITLE
Update settings.toml

### PR DESCRIPTION
**Pull request by jazy510**
Added search terms for [slave.imagesofbelize]

### CODE REVIEW

**Comment by amici-ursi** [comment]
Please double check your lines end in commas when appropriate. For example, https://github.com/amici-ursi/ImagesOfNetwork/pull/56/commits/9a2d805dcc1e13208da4f00af451c086f9d33021#diff-444c50fbc8653a213f3c9b3cd791a127R636 needs a comma.

Once you get those fixes it, we'll merge your request.

**Comment by jazy510** [comment]
ok, i've edited & i think (hope) the syntax is good now.

**Comment by scowcron** [comment]
Yep, the syntax looks good. We've got a few issues that need to be fixed before we pull this in.

First, you should rebase your branch. `slave` changed to `child` between now and when you first submitted. I don't think it'll be an issue, but better safe than sorry.

Second, you've got a couple search terms that are way too generic and will most likely produce almost exclusively false positives: `blue hole` and `shipyard` - they should be removed. We already handle 'great blue hole'.

Third, `san pedro` and `punta gorda` will produce more false positives than not. I removed them for that reason; there is a san pedro in california and a punta gorda in florida that will match more frequently. If `belize` is in the title (e.g. "Punta Gorda, Belize"), we'll catch it anyway, so that's not an issue. If you still want to have them here, i'd suggest trailing them with `, bz`.

Here's a checklist:
- [ ] rebase to origin/master
- [ ] remove `blue hole`
- [ ] remove `shipyard`
- [ ] `punta gorda, bz` or removal
- [ ] `san pedro, bz` or removal

**Comment by amici-ursi** [comment]
Looks like this was added through a separate PR.

**Pull request closed without merging**
